import { createFileRoute } from "@tanstack/react-router";
import { loadPageData } from "@/lib/cms/loaders/slug";
import { isValidSlugPath } from "@/lib/utils";
import { drizzleMiddleware } from "@/core/middleware/db-middleware";
import { PageData } from "@/lib/cms/blocks/block-registry.types";
import { eq, sql } from "drizzle-orm";
import { json } from "@tanstack/react-start";
import { blocks, pageBlocks, pages } from "@/core/db/schema";
import { authRequestMiddleware } from "@/core/middleware/auth/auth-request-middleware";

type UpdatePagePayload = {
  title?: string;
  status?: string;
  // The frontend sends the full state of blocks in their desired order
  blocks: Array<{
    id: string; // UUID (generated by frontend for new blocks)
    type: string;
    data: any; // The actual content
  }>;
};

export const Route = createFileRoute("/api/pages/$/slug")({
  server: {
    middleware: [drizzleMiddleware, authRequestMiddleware],
    handlers: {
      GET: async ({ params, context }) => {
        const slug = params._splat;
        if (!slug || !isValidSlugPath(slug)) {
          return new Response("Not Found", { status: 404 });
        }

        const data = await loadPageData(context.db, {
          slug,
          requirePublished: false,
        });

        if (!data) {
          return new Response("Not Found", { status: 404 });
        }

        return Response.json(data);
      },
      POST: async ({ request, params, context }) => {
        const { auth, db } = context;
        const slug = params._splat;

        // 1. Auth & Validation
        const session = await auth.api.getSession(request);
        if (!session?.user)
          return new Response("Unauthorized", { status: 401 });
        if (!slug || !isValidSlugPath(slug))
          return new Response("Invalid slug", { status: 400 });

        const body = (await request.json()) as UpdatePagePayload;

        // 2. Execute as a Transaction
        // If any part fails (e.g., block insert fails), the whole page update rolls back.
        await db.transaction(async (tx) => {
          // A. Get Page ID (needed for relations) & Update Metadata
          const [existingPage] = await tx
            .update(pages)
            .set({
              title: body.title, // Update title if provided
              status: body.status ?? "draft",
              updatedAt: new Date(),
            })
            .where(eq(pages.slug, slug))
            .returning({ id: pages.id });

          if (!existingPage) {
            // Rollback will happen automatically if we throw
            throw new Error("Page not found");
          }

          // B. Upsert Blocks (Insert new ones, Update existing ones)
          // We use ON CONFLICT DO UPDATE so we don't need to check if they exist.
          if (body.blocks.length > 0) {
            const blockValues = body.blocks.map((b) => ({
              id: b.id,
              type: b.type,
              data: b.data,
              updatedAt: new Date(), // Refresh timestamp
            }));

            await tx
              .insert(blocks)
              .values(blockValues)
              .onConflictDoUpdate({
                target: blocks.id,
                set: {
                  data: sql`excluded.data`,
                  updatedAt: sql`excluded.updated_at`,
                },
              });
          }

          // C. Sync Page Layout (The "Nuke and Pave" Link Strategy)
          // 1. Clear all existing associations for this page
          await tx
            .delete(pageBlocks)
            .where(eq(pageBlocks.pageId, existingPage.id));

          // 2. Insert the new list in the correct order
          if (body.blocks.length > 0) {
            const newLinks = body.blocks.map((b, index) => ({
              pageId: existingPage.id,
              blockId: b.id,
              order: index, // Uses the array index from the payload
            }));

            await tx.insert(pageBlocks).values(newLinks);
          }
        });

        return json({ ok: true });
      },
    },
  },
});
