/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRegisterRouteImport } from './routes/app/register'
import { Route as AppLoginRouteImport } from './routes/app/login'
import { Route as AppauthenticatedRouteRouteImport } from './routes/app/(authenticated)/route'
import { Route as AppauthenticatedIndexRouteImport } from './routes/app/(authenticated)/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRegisterRoute = AppRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppauthenticatedRouteRoute = AppauthenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppauthenticatedIndexRoute = AppauthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppauthenticatedRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppauthenticatedRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/app/login': typeof AppLoginRoute
  '/app/register': typeof AppRegisterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/': typeof AppauthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppauthenticatedIndexRoute
  '/$slug': typeof SlugRoute
  '/app/login': typeof AppLoginRoute
  '/app/register': typeof AppRegisterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/app/(authenticated)': typeof AppauthenticatedRouteRouteWithChildren
  '/app/login': typeof AppLoginRoute
  '/app/register': typeof AppRegisterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/(authenticated)/': typeof AppauthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/$slug'
    | '/app/login'
    | '/app/register'
    | '/api/auth/$'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/$slug' | '/app/login' | '/app/register' | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/$slug'
    | '/app/(authenticated)'
    | '/app/login'
    | '/app/register'
    | '/api/auth/$'
    | '/app/(authenticated)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  SlugRoute: typeof SlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/register': {
      id: '/app/register'
      path: '/register'
      fullPath: '/app/register'
      preLoaderRoute: typeof AppRegisterRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/login': {
      id: '/app/login'
      path: '/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(authenticated)': {
      id: '/app/(authenticated)'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppauthenticatedRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(authenticated)/': {
      id: '/app/(authenticated)/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppauthenticatedIndexRouteImport
      parentRoute: typeof AppauthenticatedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppauthenticatedRouteRouteChildren {
  AppauthenticatedIndexRoute: typeof AppauthenticatedIndexRoute
}

const AppauthenticatedRouteRouteChildren: AppauthenticatedRouteRouteChildren = {
  AppauthenticatedIndexRoute: AppauthenticatedIndexRoute,
}

const AppauthenticatedRouteRouteWithChildren =
  AppauthenticatedRouteRoute._addFileChildren(
    AppauthenticatedRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppauthenticatedRouteRoute: typeof AppauthenticatedRouteRouteWithChildren
  AppLoginRoute: typeof AppLoginRoute
  AppRegisterRoute: typeof AppRegisterRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppauthenticatedRouteRoute: AppauthenticatedRouteRouteWithChildren,
  AppLoginRoute: AppLoginRoute,
  AppRegisterRoute: AppRegisterRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  SlugRoute: SlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
