/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRegisterRouteImport } from './routes/app/register'
import { Route as AppLoginRouteImport } from './routes/app/login'
import { Route as AppauthenticatedRouteRouteImport } from './routes/app/(authenticated)/route'
import { Route as AppauthenticatedIndexRouteImport } from './routes/app/(authenticated)/index'
import { Route as ApiPagesSplatRouteImport } from './routes/api/pages/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppauthenticatedEditRouteRouteImport } from './routes/app/(authenticated)/edit/route'
import { Route as AppauthenticatedEditSplatRouteImport } from './routes/app/(authenticated)/edit/$'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRegisterRoute = AppRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppauthenticatedRouteRoute = AppauthenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppauthenticatedIndexRoute = AppauthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppauthenticatedRouteRoute,
} as any)
const ApiPagesSplatRoute = ApiPagesSplatRouteImport.update({
  id: '/api/pages/$',
  path: '/api/pages/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppauthenticatedEditRouteRoute =
  AppauthenticatedEditRouteRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppauthenticatedRouteRoute,
  } as any)
const AppauthenticatedEditSplatRoute =
  AppauthenticatedEditSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => AppauthenticatedEditRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppauthenticatedRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/app/login': typeof AppLoginRoute
  '/app/register': typeof AppRegisterRoute
  '/app/edit': typeof AppauthenticatedEditRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/pages/$': typeof ApiPagesSplatRoute
  '/app/': typeof AppauthenticatedIndexRoute
  '/app/edit/$': typeof AppauthenticatedEditSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppauthenticatedIndexRoute
  '/$': typeof SplatRoute
  '/app/login': typeof AppLoginRoute
  '/app/register': typeof AppRegisterRoute
  '/app/edit': typeof AppauthenticatedEditRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/pages/$': typeof ApiPagesSplatRoute
  '/app/edit/$': typeof AppauthenticatedEditSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/app/(authenticated)': typeof AppauthenticatedRouteRouteWithChildren
  '/app/login': typeof AppLoginRoute
  '/app/register': typeof AppRegisterRoute
  '/app/(authenticated)/edit': typeof AppauthenticatedEditRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/pages/$': typeof ApiPagesSplatRoute
  '/app/(authenticated)/': typeof AppauthenticatedIndexRoute
  '/app/(authenticated)/edit/$': typeof AppauthenticatedEditSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/$'
    | '/app/login'
    | '/app/register'
    | '/app/edit'
    | '/api/auth/$'
    | '/api/pages/$'
    | '/app/'
    | '/app/edit/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/$'
    | '/app/login'
    | '/app/register'
    | '/app/edit'
    | '/api/auth/$'
    | '/api/pages/$'
    | '/app/edit/$'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/$'
    | '/app/(authenticated)'
    | '/app/login'
    | '/app/register'
    | '/app/(authenticated)/edit'
    | '/api/auth/$'
    | '/api/pages/$'
    | '/app/(authenticated)/'
    | '/app/(authenticated)/edit/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPagesSplatRoute: typeof ApiPagesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/register': {
      id: '/app/register'
      path: '/register'
      fullPath: '/app/register'
      preLoaderRoute: typeof AppRegisterRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/login': {
      id: '/app/login'
      path: '/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(authenticated)': {
      id: '/app/(authenticated)'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppauthenticatedRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(authenticated)/': {
      id: '/app/(authenticated)/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppauthenticatedIndexRouteImport
      parentRoute: typeof AppauthenticatedRouteRoute
    }
    '/api/pages/$': {
      id: '/api/pages/$'
      path: '/api/pages/$'
      fullPath: '/api/pages/$'
      preLoaderRoute: typeof ApiPagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/(authenticated)/edit': {
      id: '/app/(authenticated)/edit'
      path: '/edit'
      fullPath: '/app/edit'
      preLoaderRoute: typeof AppauthenticatedEditRouteRouteImport
      parentRoute: typeof AppauthenticatedRouteRoute
    }
    '/app/(authenticated)/edit/$': {
      id: '/app/(authenticated)/edit/$'
      path: '/$'
      fullPath: '/app/edit/$'
      preLoaderRoute: typeof AppauthenticatedEditSplatRouteImport
      parentRoute: typeof AppauthenticatedEditRouteRoute
    }
  }
}

interface AppauthenticatedEditRouteRouteChildren {
  AppauthenticatedEditSplatRoute: typeof AppauthenticatedEditSplatRoute
}

const AppauthenticatedEditRouteRouteChildren: AppauthenticatedEditRouteRouteChildren =
  {
    AppauthenticatedEditSplatRoute: AppauthenticatedEditSplatRoute,
  }

const AppauthenticatedEditRouteRouteWithChildren =
  AppauthenticatedEditRouteRoute._addFileChildren(
    AppauthenticatedEditRouteRouteChildren,
  )

interface AppauthenticatedRouteRouteChildren {
  AppauthenticatedEditRouteRoute: typeof AppauthenticatedEditRouteRouteWithChildren
  AppauthenticatedIndexRoute: typeof AppauthenticatedIndexRoute
}

const AppauthenticatedRouteRouteChildren: AppauthenticatedRouteRouteChildren = {
  AppauthenticatedEditRouteRoute: AppauthenticatedEditRouteRouteWithChildren,
  AppauthenticatedIndexRoute: AppauthenticatedIndexRoute,
}

const AppauthenticatedRouteRouteWithChildren =
  AppauthenticatedRouteRoute._addFileChildren(
    AppauthenticatedRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppauthenticatedRouteRoute: typeof AppauthenticatedRouteRouteWithChildren
  AppLoginRoute: typeof AppLoginRoute
  AppRegisterRoute: typeof AppRegisterRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppauthenticatedRouteRoute: AppauthenticatedRouteRouteWithChildren,
  AppLoginRoute: AppLoginRoute,
  AppRegisterRoute: AppRegisterRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPagesSplatRoute: ApiPagesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
